### ISSUE TITLE
关于黑色刮刮乐文字特效

### ISSUE THREAD

**Issue by wyz-2015** [HCl-10/chaoli-books#1]
是否需要在这里也加入类似[这样](https://antimony.fandom.com/zh/wiki/Template:Black)的文字特效呢？恶搞性文章里似乎常需要用到这个呢。

**Comment by HCl-10** [comment]
可以，但是可能会麻烦一些
特效的代码需要手动写

**Comment by HCl-10** [comment]
效果已经加入了，使用过程中如果有什么其他问题的话可以在这里继续讨论

http://b.hcl10.ml/ralun/

**Comment by HCl-10** [comment]
目前刮刮乐特效有两种类型
`class="heimu"` 为普通型，适用于白色文字
`class="foot-heimu"` 为注释型，适用于灰色文字
